#use triple quotes for multiline string
a = ''' MY NAME IS ABHISHEK. I AM PURSUING MY BTECH IN COMPUTER SCIENCE.
      I AM LEARNING PYTHON PROGRAMMING LANGUAGE. I AM A BEGINNER IN THIS LANGUAGE.
      I AM LEARNING PYTHON FROM YOUTUBE. I AM LEARNING PYTHON FROM CODING NINJA. I AM LEARNING PYTHON FROM W3SCHOOLS. I AM LEARNING PYTHON FROM GEEKSFORGEEKS.'''
    
print(a)      

#for new line use \n
a = "MY NAME IS ABHISHEK. I AM PURSUING MY BTECH IN COMPUTER SCIENCE.\nI AM LEARNING PYTHON PROGRAMMING LANGUAGE.\nI AM A BEGINNER IN THIS LANGUAGE.\nI AM LEARNING PYTHON FROM YOUTUBE.\nI AM LEARNING PYTHON FROM CODING NINJA.\nI AM LEARNING PYTHON FROM W3SCHOOLS.\nI AM LEARNING PYTHON FROM GEEKSFORGEEKS."
print(a)